DROP DATABASE ONIBUS;

CREATE DATABASE ONIBUS;

USE ONIBUS;



CREATE TABLE CAD_MOTORISTA (
  COD_MOT DECIMAL(6,0) NOT NULL,
  MOT_NAME VARCHAR(40) DEFAULT NULL,
  ENDERECO_M VARCHAR(40) DEFAULT NULL,
  NUMERO_M DECIMAL(4,0) DEFAULT NULL,
  BAIRRO_M VARCHAR(20) DEFAULT NULL,
  CIDADE_M VARCHAR(30) DEFAULT NULL,
  ESTADO_M CHAR(2) DEFAULT NULL,
  CEP_M DECIMAL(9,0) DEFAULT NULL,
  FONE_M DECIMAL(20,0) DEFAULT NULL,
  MOT_NASC DATETIME DEFAULT NULL,
  CNH_VENC DATETIME DEFAULT NULL,
  CNH_TIPO CHAR(1) DEFAULT NULL,
  PRIMARY KEY (COD_MOT)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;



CREATE TABLE CAD_ONIBUS (
  PLACA VARCHAR(8) NOT NULL,
  MARCA VARCHAR(20) DEFAULT NULL,
  TIPO_AUTO CHAR(1) DEFAULT NULL,
  FAB_ANO DECIMAL(4,0) DEFAULT NULL,
  NUM_ASSENTO DECIMAL(3,0) DEFAULT NULL,
  OBS_AUTO VARCHAR(1000) DEFAULT NULL,
  PRIMARY KEY (PLACA)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;



CREATE TABLE CAD_PASSAGEIRO (
  CPF DECIMAL(14,0) NOT NULL,
  PASS_NAME VARCHAR(40) DEFAULT NULL,
  CIDADE_P VARCHAR(30) DEFAULT NULL,
  ESTADO_P CHAR(2) DEFAULT NULL,
  PASS_NASC DATETIME DEFAULT NULL,
  OBS_PASS VARCHAR(1000) DEFAULT NULL,
  PRIMARY KEY (CPF)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;



CREATE TABLE CAD_PERCURSO (
  ROTA VARCHAR(60) NOT NULL,
  PER_TEMP VARCHAR(10) DEFAULT NULL,
  TROCAR_MOT CHAR(1) DEFAULT NULL,
  QTDE_MOT DECIMAL(2,0) DEFAULT NULL,
  OPEN_VENDAS CHAR(1) DEFAULT NULL,
  PASS_VALOR DECIMAL(12,2) DEFAULT NULL,
  PASS_BAG DECIMAL(12,2) DEFAULT NULL,
  PRIMARY KEY (ROTA)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;



CREATE TABLE CAD_USUARIOS (
  USER_NAME VARCHAR(40) DEFAULT NULL,
  USER_FONE DECIMAL(20,0) DEFAULT NULL,
  TIPO CHAR(1) DEFAULT NULL,
  USER_ID VARCHAR(15) NOT NULL,
  SENHA VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (USER_ID)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;



CREATE TABLE LCMT_VIAGEM (
  DATA_VIAGEM DATETIME NOT NULL,
  ROTA2 VARCHAR(60) NOT NULL,
  PLACA2 VARCHAR(8) DEFAULT NULL,
  COD_MOT2 DECIMAL(6,0) DEFAULT NULL,
  PRIMARY KEY (DATA_VIAGEM,ROTA2)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;



CREATE TABLE LCMT_VIAGEM_PASS (
  DATA_VIAGEM2 DATETIME NOT NULL,
  ROTA3 VARCHAR(60) NOT NULL,
  NUM_ASSENTO DECIMAL(3,0) DEFAULT NULL,
  CPF2 DECIMAL(14,0) DEFAULT NULL,
  AUTO_VGM CHAR(1) DEFAULT NULL,
  NUM_BAG DECIMAL(3,0) DEFAULT NULL,
  PRIMARY KEY (DATA_VIAGEM2,ROTA3)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;




